{
 "title": "CP Dashboard - VSX",
 "tags": [ "Skyline" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "d_environment",
    "label": "Environment:",
    "query": {
     "query": "label_values(system_gaia_os_role{role=~\".*VSX.*\"},environment)"
    }
   },
   {
    "name": "d_hostname",
    "label": "Hostname:",
    "query": {
     "query": "label_values(system_gaia_os_role{role=~\".*VSX.*\", environment=~\"$d_environment\"},host_name)"
    }
   },
   { "name": "d_namespace", "label": "Context:", "query": "vs_id_0" }
  ]
 },
 "panels": [
  { "title": "VSX General Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VS Count",
   "type": "stat",
   "description": "Virtual Systems count excluding VS0",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(system_uptime{host_name=~\"$d_hostname\", environment=~\"$d_environment\"}) - 1"
    }
   ]
  },
  {
   "title": "VSX General Info",
   "type": "table",
   "description": "VSX overview originating from VS0 only ",
   "gridPos": { "h": 6, "w": 13, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "vsx_overview{host_name=~\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}"
    }
   ]
  },
  {
   "title": "VSX Dynamic Info",
   "type": "table",
   "description": "VSX dynamic information from each of the VSs",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "system_network_tcp_out_of_state_drops_state{host_name=\"$d_hostname\", environment=~\"$d_environment\"}"
    }
   ]
  },
  {
   "title": "System Overview - Info / CPU / Mem / Disk/Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Role",
   "type": "stat",
   "description": "Machine Role",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_gaia_os_role{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\", role=~\".+\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "stat",
   "description": "Version of the OS",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_gaia_os_version{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\", version=~\".+\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_count{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"}"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AVG(100-system_cpu_utilization{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"idle\"})"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_usage{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"used\"} / ignoring (state) system_memory_limit{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"} * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_usage_swap_used{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}/system_memory_usage_swap_total{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"} * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "\"/\" partition usage",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_filesystem_usage{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", mountpoint=\"/\", state=\"used\"} / ignoring (state) system_filesystem_limit{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", mountpoint=\"/\"} * 100"
    }
   ]
  },
  {
   "title": "Logs FS Used",
   "type": "gauge",
   "description": "\"/var/log\" partition usage",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_filesystem_usage{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", mountpoint=\"/var/log\", state=\"used\"} / ignoring (state) system_filesystem_limit{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", mountpoint=\"/var/log\"} * 100"
    }
   ]
  },
  {
   "title": "CPU Load Comparison",
   "type": "bargauge",
   "description": "CPU load  comparison by types",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (type) (100-system_cpu_utilization{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"idle\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "OS Edition",
   "type": "stat",
   "description": "OS Edition",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_gaia_os_edition{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\", edition=~\".+\"}",
     "legendFormat": "{{edition}}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_filesystem_limit{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\", mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Uptime since last reboot",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"}"
    }
   ]
  },
  {
   "title": "FW build",
   "type": "stat",
   "description": "FW build version",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_gaia_module_version{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\", module=~\"Firewall-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_limit{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"}"
    }
   ]
  },
  {
   "title": "Top VSs- Transmit",
   "type": "bargauge",
   "description": "Top  VSs with the highest TX traffic",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, sum by (service_namespace) (system_network_interface_tx_throughput_bs{host_name=\"$d_hostname\", environment=~\"$d_environment\", if_name!~\"TOTAL|lo\"}))\r\n",
     "legendFormat": "{{service_namespace}}"
    }
   ]
  },
  {
   "title": "Top VSs-  Receive",
   "type": "bargauge",
   "description": "Top VSs with the highest RX traffic",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3, sum by (service_namespace) (system_network_interface_rx_throughput_bs{host_name=\"$d_hostname\", environment=~\"$d_environment\", if_name!~\"TOTAL|lo\"}))",
     "legendFormat": "{{service_namespace}}"
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "stat",
   "description": "Hardware Model",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hardware_model{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP ",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_paging_limit{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"vs_id_0\"}"
    }
   ]
  },
  {
   "title": "Basic CPU / Mem / Net / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Basic",
     "type": "timeseries",
     "description": "Basic CPU info",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(system_cpu_utilization{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"system\"})",
       "legendFormat": "Busy System"
      },
      {
       "expr": "sum(system_cpu_utilization{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"user\"})",
       "legendFormat": "Busy User"
      },
      {
       "expr": "sum(system_cpu_utilization{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"io wait\"})",
       "legendFormat": "Busy Iowait"
      },
      {
       "expr": "sum(system_cpu_utilization{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"idle\"})",
       "legendFormat": "Idle"
      }
     ]
    },
    {
     "title": "Memory  Basic",
     "type": "timeseries",
     "description": "Basic memory usage",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "system_memory_usage_real_total{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}",
       "legendFormat": "RAM Total"
      },
      {
       "expr": "system_memory_usage{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"used\"}",
       "legendFormat": "RAM Used"
      },
      {
       "expr": "system_memory_usage{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"free\"}",
       "legendFormat": "RAM Free"
      },
      {
       "expr": "system_paging_usage{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"used\"}",
       "legendFormat": "Swap Used"
      }
     ]
    },
    {
     "title": "Disk Space (Percentage)",
     "type": "timeseries",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "(system_filesystem_usage{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"used\"}/ ignoring (state) system_filesystem_limit{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}) * 100",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Network Basic",
     "type": "timeseries",
     "description": "Network traffic in bits/sec",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "SUM(system_network_interface_io_receive_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface!~\"TOTAL|lo\"})",
       "legendFormat": "Receive"
      },
      {
       "expr": "sum(system_network_interface_io_transmit_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface!~\"TOTAL|lo\"})",
       "legendFormat": "Transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU / Memory / Net / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage By Cores",
     "type": "timeseries",
     "description": "CPU usage by cores",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100-system_cpu_utilization{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"idle\"}",
       "legendFormat": "CPU{{cpu}} - {{type}}"
      }
     ]
    },
    {
     "title": "CPU Interrupts",
     "type": "timeseries",
     "description": "CPU Interrupts info",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (cpu) (system_cpu_interrupts{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"})",
       "legendFormat": "CPU{{cpu}}"
      }
     ]
    },
    {
     "title": "Disk Space ",
     "type": "timeseries",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "system_filesystem_usage{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"used\"}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Network traffic per interface in bits/sec",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "sum by (interface) (system_network_interface_io_receive_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface!~\"TOTAL|lo\"})",
       "legendFormat": "{{interface}} - Receive"
      },
      {
       "expr": "sum by (interface) (system_network_interface_io_transmit_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface!~\"TOTAL|lo\"})",
       "legendFormat": "{{interface}} - Transmit"
      }
     ]
    },
    {
     "title": "Packets Traffic",
     "type": "timeseries",
     "description": "Network traffic per interface by packets/sec ",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (interface) (system_network_interface_packets_receive_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface!~\"TOTAL|lo\"})",
       "legendFormat": "{{interface}} - Receive"
      },
      {
       "expr": "sum by (interface) (system_network_interface_packets_transmit_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface!~\"TOTAL|lo\"})",
       "legendFormat": "{{interface}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Drops",
     "type": "timeseries",
     "description": "Network drops per interface",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (interface) (system_network_dropped_receive{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface!~\"TOTAL|lo\"})",
       "legendFormat": "{{interface}} - RX"
      },
      {
       "expr": "sum by (interface) (system_network_dropped_transmit{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface!~\"TOTAL|lo\"})",
       "legendFormat": "{{interface}} - TX"
      }
     ]
    },
    {
     "title": "Concurrent Connections",
     "type": "timeseries",
     "description": "Concurrent connections by type",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "SUM(system_traffic_connections{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", protocol=\"other\"})",
       "legendFormat": "Non-TCP Connections"
      },
      {
       "expr": "SUM(system_traffic_connections{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", protocol=\"tcp\", state=\"handshake\"})",
       "legendFormat": "TCP Handshake Connections"
      },
      {
       "expr": "SUM(system_traffic_connections{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", protocol=\"tcp\", state=\"established\"})",
       "legendFormat": "TCP Established Connections"
      },
      {
       "expr": "SUM(system_traffic_connections{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", protocol=\"tcp\", state=\"closed\"})",
       "legendFormat": "TCP Closed Connections"
      }
     ]
    },
    {
     "title": "Connection Drops",
     "type": "timeseries",
     "description": "Connection drops by type",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (type) (system_traffic_dropped{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Connection Rate",
     "type": "timeseries",
     "description": "Connection rate per second",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "SUM(system_network_connections_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"})",
       "legendFormat": "Connections rate per second"
      }
     ]
    }
   ]
  },
  {
   "title": "Network - Per VS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic  - Per VS",
     "type": "timeseries",
     "description": "Network Traffic info per VS in bits/sec",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "sum by (service_namespace) (system_network_interface_io_receive_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", interface!~\"TOTAL|lo\"})",
       "legendFormat": "{{service_namespace}} - Receive"
      },
      {
       "expr": "sum by (service_namespace) (system_network_interface_io_transmit_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", interface!~\"TOTAL|lo\"})",
       "legendFormat": "{{service_namespace}} - Transmit"
      }
     ]
    },
    {
     "title": "Packets Traffic - Per VS",
     "type": "timeseries",
     "description": "Network info per VS in packets/sec",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (service_namespace) (system_network_interface_packets_receive_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", interface!~\"TOTAL|lo\"})",
       "legendFormat": "{{service_namespace}} - Receive"
      },
      {
       "expr": "sum by (service_namespace) (system_network_interface_packets_transmit_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", interface!~\"TOTAL|lo\"})",
       "legendFormat": "{{service_namespace}} - Transmit"
      }
     ]
    },
    {
     "title": "Drops - Per VS",
     "type": "timeseries",
     "description": "Drops info per VS context",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (service_namespace) (system_network_dropped_receive{host_name=\"$d_hostname\", environment=~\"$d_environment\", interface!~\"TOTAL|lo\"})",
       "legendFormat": "{{service_namespace}} - RX"
      },
      {
       "expr": "sum by (service_namespace) (system_network_dropped_transmit{host_name=\"$d_hostname\", environment=~\"$d_environment\", interface!~\"TOTAL|lo\"})",
       "legendFormat": "{{service_namespace}} - TX"
      }
     ]
    },
    {
     "title": "Concurrent Connections - Per VS",
     "type": "timeseries",
     "description": "Concurrent connections Per VS",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (service_namespace) (system_traffic_connections{host_name=\"$d_hostname\", environment=~\"$d_environment\", protocol=\"other\"})",
       "legendFormat": "Non-TCP Connections - {{service_namespace}}"
      },
      {
       "expr": "sum by (service_namespace) (system_traffic_connections{host_name=\"$d_hostname\", environment=~\"$d_environment\", protocol=\"tcp\", state=\"handshake\"})",
       "legendFormat": "TCP Handshake Connections  - {{service_namespace}}"
      },
      {
       "expr": "sum by (service_namespace) (system_traffic_connections{host_name=\"$d_hostname\", environment=~\"$d_environment\", protocol=\"tcp\", state=\"established\"})",
       "legendFormat": "TCP Established Connections  - {{service_namespace}}"
      },
      {
       "expr": "sum by (service_namespace) (system_traffic_connections{host_name=\"$d_hostname\", environment=~\"$d_environment\", protocol=\"tcp\", state=\"closed\"})",
       "legendFormat": "TCP Closed Connections  - {{service_namespace}}"
      }
     ]
    },
    {
     "title": "Connection Drops - Per VS",
     "type": "timeseries",
     "description": "Connection drops by type",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (type,service_namespace) (system_traffic_dropped{host_name=\"$d_hostname\", environment=~\"$d_environment\"})",
       "legendFormat": "{{service_namespace}} - {{type}} "
      }
     ]
    },
    {
     "title": "Connection Rate - Per VS",
     "type": "timeseries",
     "description": "Connection rate per second",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "sum by (service_namespace)(system_network_connections_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\"})",
       "legendFormat": "Connection rate per second - {{service_namespace}}"
      }
     ]
    }
   ]
  }
 ]
}