{
 "title": "CP_Dashboard_Single_Machine",
 "tags": [ "Skyline" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "d_environment",
    "label": "Environment:",
    "query": {
     "query": "label_values(system_uptime,environment)"
    }
   },
   {
    "name": "d_hostname",
    "label": "Hostname:",
    "query": {
     "query": "label_values(system_uptime{environment=~\"$d_environment\"},host_name)"
    }
   },
   {
    "name": "d_namespace",
    "label": "Context:",
    "query": {
     "query": "label_values(system_uptime{host_name=\"$d_hostname\", environment=~\"$d_environment\"}, service_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System Overview - Info / CPU / Mem / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Role",
   "type": "stat",
   "description": "Machine Role",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_gaia_os_role{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", role=~\".+\"}",
     "legendFormat": "{{role}}"
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "stat",
   "description": "Version of the OS",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_gaia_os_version{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", version=~\".+\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu_count{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}"
    }
   ]
  },
  {
   "title": "Policy Installed",
   "type": "stat",
   "description": "Installed policy name",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "firewall_policy_name{name=~\".+\", host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"$d_namespace\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "AVG(100-system_cpu_utilization{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"idle\"})"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 2, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_usage{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"used\"} / ignoring (state) system_memory_limit{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"} * 100"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "description": "Used Swap",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_paging_usage{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"used\"} / ignoring (state) system_paging_limit{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"} * 100"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "description": "\"/\" partition usage",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_filesystem_usage{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", mountpoint=\"/\", state=\"used\"} / ignoring (state) system_filesystem_limit{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", mountpoint=\"/\"} * 100"
    }
   ]
  },
  {
   "title": "Logs FS Used",
   "type": "gauge",
   "description": "\"/var/log\" partition usage",
   "gridPos": { "h": 4, "w": 2, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_filesystem_usage{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", mountpoint=\"/var/log\", state=\"used\"} / ignoring (state) system_filesystem_limit{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", mountpoint=\"/var/log\"} * 100"
    }
   ]
  },
  {
   "title": "TCP Out Of State Drops Status",
   "type": "stat",
   "description": "TCP Out Of State Drops Status",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_network_tcp_out_of_state_drops_state{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}"
    }
   ]
  },
  {
   "title": "OS Edition",
   "type": "stat",
   "description": "OS Edition",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_gaia_os_edition{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", edition=~\".+\"}",
     "legendFormat": "{{edition}}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory_limit{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}"
    }
   ]
  },
  {
   "title": "Policy date",
   "type": "stat",
   "description": "Time of last policy installation",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(firewall_policy_time{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=\"$d_namespace\"}>100000)*1000"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Uptime since last reboot",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}"
    }
   ]
  },
  {
   "title": "FW build",
   "type": "stat",
   "description": "FW build version",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_gaia_module_version{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", module=~\"Firewall-1\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SWAP Total",
   "type": "stat",
   "description": "Total SWAP ",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_paging_limit{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}"
    }
   ]
  },
  {
   "title": "CPU Load Comparison",
   "type": "bargauge",
   "description": "CPU load  comparison by types",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (type) (100-system_cpu_utilization{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"idle\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Top interfaces - Receive",
   "type": "bargauge",
   "description": "Top interfaces with the highest RX traffic since last boot",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(2,system_network_interface_io_receive_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface!~\"TOTAL|lo\"})",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Top interfaces - Transmit",
   "type": "bargauge",
   "description": "Top interfaces with the highest TX traffic since last boot",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(2,system_network_interface_io_transmit_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface!~\"TOTAL|lo\"})",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "stat",
   "description": "Hardware Model",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hardware_model{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}",
     "legendFormat": "{{model}}"
    }
   ]
  },
  {
   "title": "RootFS Total",
   "type": "stat",
   "description": "Total RootFS",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_filesystem_limit{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", mountpoint=\"/\"}"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Net / Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "description": "Basic CPU info",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(system_cpu_utilization{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"system\"})",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum(system_cpu_utilization{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"user\"})",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum(system_cpu_utilization{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"io wait\"})",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum(system_cpu_utilization{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"idle\"})",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "Memory  Basic",
   "type": "timeseries",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "system_memory_usage_real_total{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "system_memory_usage{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"used\"}",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "system_memory_usage{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"free\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "system_paging_usage{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"used\"}",
     "legendFormat": "Swap Used"
    }
   ]
  },
  {
   "title": "Disk Space (Percentage)",
   "type": "timeseries",
   "description": "Disk space used of all filesystems mounted",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(system_filesystem_usage{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"used\"}/ ignoring (state) system_filesystem_limit{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"}) * 100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Basic",
   "type": "timeseries",
   "description": "Network traffic in bits/sec",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "SUM(system_network_interface_io_receive_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface!~\"TOTAL|lo\"})",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum(system_network_interface_io_transmit_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface!~\"TOTAL|lo\"})",
     "legendFormat": "Transmit"
    }
   ]
  },
  {
   "title": "CPU / Memory / Net / Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage By Cores",
     "type": "timeseries",
     "description": "CPU usage by cores",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100-system_cpu_utilization{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"idle\"}",
       "legendFormat": "CPU{{cpu}} - {{type}}"
      }
     ]
    },
    {
     "title": "CPU Interrupts",
     "type": "timeseries",
     "description": "CPU Interrupts info",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (cpu) (system_cpu_interrupts{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"})",
       "legendFormat": "CPU{{cpu}}"
      }
     ]
    },
    {
     "title": "Disk Space ",
     "type": "timeseries",
     "description": "Disk space used of all filesystems mounted",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "system_filesystem_usage{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", state=\"used\"}",
       "legendFormat": "{{mountpoint}}"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "timeseries",
     "description": "Network traffic per interface in bits/sec",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "sum by (interface) (system_network_interface_io_receive_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface!~\"TOTAL|lo\"})",
       "legendFormat": "{{interface}} - Receive"
      },
      {
       "expr": "sum by (interface) (system_network_interface_io_transmit_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface!~\"TOTAL|lo\"})",
       "legendFormat": "{{interface}} - Transmit"
      }
     ]
    },
    {
     "title": "Packets Traffic",
     "type": "timeseries",
     "description": "Network traffic per interface by packets/sec ",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (interface) (system_network_interface_packets_receive_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface!~\"TOTAL|lo\"})",
       "legendFormat": "{{interface}} - Receive"
      },
      {
       "expr": "sum by (interface) (system_network_interface_packets_transmit_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface!~\"TOTAL|lo\"})",
       "legendFormat": "{{interface}} - Transmit"
      }
     ]
    },
    {
     "title": "Network Drops",
     "type": "timeseries",
     "description": "Network drops per interface",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (interface) (system_network_dropped_receive{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface!~\"TOTAL|lo\"})",
       "legendFormat": "{{interface}} - RX"
      },
      {
       "expr": "sum by (interface) (system_network_dropped_transmit{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface!~\"TOTAL|lo\"})",
       "legendFormat": "{{interface}} - TX"
      }
     ]
    },
    {
     "title": "Concurrent Connections",
     "type": "timeseries",
     "description": "Concurrent connections by type",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "SUM(system_traffic_connections{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", protocol=\"other\"})",
       "legendFormat": "Non-TCP Connections"
      },
      {
       "expr": "SUM(system_traffic_connections{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", protocol=\"tcp\", state=\"handshake\"})",
       "legendFormat": "TCP Handshake Connections"
      },
      {
       "expr": "SUM(system_traffic_connections{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", protocol=\"tcp\", state=\"established\"})",
       "legendFormat": "TCP Established Connections"
      },
      {
       "expr": "SUM(system_traffic_connections{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", protocol=\"tcp\", state=\"closed\"})",
       "legendFormat": "TCP Closed Connections"
      }
     ]
    },
    {
     "title": "Connection Drops",
     "type": "timeseries",
     "description": "Connection drops by type",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (type) (system_traffic_dropped{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"})",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Connection Rate",
     "type": "timeseries",
     "description": "Connection rate per second",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "SUM(system_network_connections_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\"})",
       "legendFormat": "Connections rate per second"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Interfaces Info",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "system_network_interface_state{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", name=~\".+\"}"
      },
      {
       "expr": "system_network_interface_address{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", name=~\".+\", address=~\".+\"}"
      }
     ]
    },
    {
     "title": "Network Interfaces RX Traffic",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "system_network_packets_receive{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface=~\".+\"}"
      },
      {
       "expr": "system_network_interface_packets_receive_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface=~\".+\"}"
      },
      {
       "expr": "system_network_interface_packets_receive_rate_peak{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface=~\".+\"}"
      },
      {
       "expr": "system_network_dropped_receive{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface=~\".+\"}"
      },
      {
       "expr": "system_network_errors_receive{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface=~\".+\"}"
      }
     ]
    },
    {
     "title": "Network Interfaces TX Traffic",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "system_network_packets_transmit{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface=~\".+\"}"
      },
      {
       "expr": "system_network_interface_packets_transmit_rate{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface=~\".+\"}"
      },
      {
       "expr": "system_network_interface_packets_transmit_rate_peak{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface=~\".+\"}"
      },
      {
       "expr": "system_network_dropped_transmit{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface=~\".+\"}"
      },
      {
       "expr": "system_network_errors_transmit{host_name=\"$d_hostname\", environment=~\"$d_environment\", service_namespace=~\"$d_namespace\", interface=~\".+\"}"
      }
     ]
    }
   ]
  }
 ]
}